# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# Pour utiliser un parametre global à l'application, il faut utiliser le service parameterBag
parameters:
    app.adminMail: '%env(string:ADMIN_MAIL)%'
    app.onMaintenance: '%env(bool:ON_MAINTENANCE)%'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\SendMailService:
        arguments:
            $adminMail: '%app.adminMail%'
    App\Service\MySlugger:
        arguments:
            $toLower: '%env(bool:TO_LOWER)%'
    App\EventSubscriber\MaintenanceSubscriber:
        arguments:
            $onMaintenance: '%app.onMaintenance%'
    App\Service\OmdbApi:
        arguments:
            $apiKey: '%env(string:API_KEY)%'
    App\EventListener\MovieListener:
        tags:
            -
                # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'App\Entity\Movie'
                method: "changeSlug"
            -
                # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                event: 'prePersist'
                entity: 'App\Entity\Movie'
                method: "changeSlug"
    App\EventListener\ReviewListener:
        tags:
            -
                # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Review'
                method: "CalculMovieRating"
    App\Normalizer\EntityNormalizer:
        public: false
        autowire: true
        autoconfigure: true
        tags: [serializer.normalizer]